name: CI

on:
  pull_request:
    types: [opened, review_requested, edited, synchronize]
    branches: 
      - "**"

jobs:
  development-ci:
    name: development-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: install dependencies
        run: yarn
          
      - name: linting
        run: yarn lint
          
      - name: run unit tests with coverage
        run: yarn test:coverage
          
      - name: upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          
      - name: build
        run: yarn build
          
      - name: install playwright browsers
        run: npx playwright install --with-deps chromium
          
      - name: run e2e tests
        run: yarn test:e2e
        env:
          CI: true